server {
    listen 80;
    server_name explorer.eltx.online;

    location / {
        proxy_pass http://blockscout:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 30s;
        proxy_read_timeout 180s;
    }

    location /healthz {
        proxy_pass http://blockscout:4001/healthz;
        proxy_set_header Host $host;
    }

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "SAMEORIGIN";
}
